services:     
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/config/default.conf:/etc/nginx/conf.d/default.conf
#      - ./data/ssl/public.pem:/etc/nginx/conf.d/public.pem
#      - ./data/ssl/private.key:/etc/nginx/conf.d/private.key
      - ./data/images:/home
    depends_on:
      - next-app
    networks:
      - dev_network

  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
    restart: always
    env_file: .env.production
    volumes:
      - ./data/images/uploads:/app/uploads
      - ./data/config/address.json:/app/config/address.json
    ports:
      - 3000:3000
    links:
      - daism-mysql
    networks:
      - dev_network

  daism-mysql:
    container_name: mysqldb
    build:
      context: ./mysql
      dockerfile: prod.Dockerfile
    restart: always
#    command: [
#            '--character-set-server=utf8mb4',
#            '--collation-server=utf8mb4_unicode_ci',
#            '--default-authentication-plugin=caching_sha2_password'            
#            ]
    environment:
      MYSQL_ROOT_PASSWORD: 'Dao..123'
    volumes:
      - ./data/mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    networks:
      - dev_network

  daism-daoserver:
    container_name: daoserver
    build:
      context: ./daolisten
      dockerfile: prod.Dockerfile
    volumes:
      - ./data/config/address.json:/app/config/address.json
      - ./data/images/uploads/logo:/app/images
    links:
      - daism-mysql
    restart: always
    env_file: .env.production
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge


